import { google } from 'googleapis';
import type { OAuth2Client } from 'google-auth-library';
import { truncate } from '@/lib/utils';
import type { CalendarEvent } from '@/types';

/** Dedicated calendar name — pushes must never touch the user's primary calendar. */
export const CALENDAR_NAME = 'Marketing OS';

/** Google Calendar's numbered event colours (1–11). Picked for rough platform association. */
const PLATFORM_COLOR_IDS: Record<string, string> = {
  tiktok: '11', // tomato
  instagram: '4', // flamingo
  facebook: '9', // blueberry
  linkedin: '7', // peacock
  xiaohongshu: '6', // tangerine
};
const DEFAULT_COLOR_ID = '8'; // graphite

function colorIdForPlatform(platform: string): string {
  const key = platform.toLowerCase().replace(/[^a-z]/g, '');
  return PLATFORM_COLOR_IDS[key] ?? DEFAULT_COLOR_ID;
}

function nextDay(isoDate: string): string {
  const date = new Date(`${isoDate}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + 1);
  return date.toISOString().slice(0, 10);
}

/** Finds the dedicated calendar by name, creating it if this is the first push. */
async function findOrCreateCalendarId(client: OAuth2Client): Promise<string> {
  const calendarApi = google.calendar({ version: 'v3', auth: client });

  const list = await calendarApi.calendarList.list();
  const existing = list.data.items?.find((entry) => entry.summary === CALENDAR_NAME);
  if (existing?.id) return existing.id;

  const created = await calendarApi.calendars.insert({ requestBody: { summary: CALENDAR_NAME } });
  if (!created.data.id) {
    throw new Error('Google Calendar did not return a calendar id.');
  }

  return created.data.id;
}

interface PushEventsResult {
  created: number;
  calendarUrl: string;
}

/** Pushes one all-day event per content item onto the dedicated "Marketing OS" calendar. */
export async function pushEventsToCalendar(client: OAuth2Client, events: CalendarEvent[]): Promise<PushEventsResult> {
  const calendarApi = google.calendar({ version: 'v3', auth: client });
  const calendarId = await findOrCreateCalendarId(client);

  let created = 0;

  for (const event of events) {
    const summary = `[${event.platform}] ${event.format} — ${truncate(event.hook, 50)}`;
    const description = [event.caption, 'Generated by Marketing OS'].filter(Boolean).join('\n\n');

    await calendarApi.events.insert({
      calendarId,
      requestBody: {
        summary,
        description,
        // All-day events: Google Calendar's `end.date` is exclusive, so a single-day event needs
        // end = start + 1 day, not the same date twice.
        start: { date: event.date },
        end: { date: nextDay(event.date) },
        colorId: colorIdForPlatform(event.platform),
      },
    });
    created += 1;
  }

  return {
    created,
    calendarUrl: `https://calendar.google.com/calendar/r?cid=${encodeURIComponent(calendarId)}`,
  };
}
